fix #80: alpha pending parses repo path
radiasoft/pykern pull request #119
Opened 2022-02-10 23:56 UTC by rorour

2022-02-11 18:57 UTC, e-carlin commented
@rorour I think we now have access to use the test-pykern-github repo.

You should be able to run the test with `PYKERN_PKCLI_GITHUB_USER='rorour' PYKERN_PKCLI_GITHUB_PASSWORD=$GITHUB_PAT pykern test tests/pkcli/github_test.py`

It looks like in the non full_path case the repo name is being added to the issue. For example this issue https://github.com/radiasoft/test-pykern-github/issues/196 has `EsZDH9wxwzv91Fzy for github_test test-pykern-github#192` and I think that line should be just `EsZDH9wxwzv91Fzy for github_test #192`. The full_path case looks good tho!

2022-02-11 21:09 UTC, e-carlin reviewed
Woops had these comments too but forgot to submit my review. Sorry

2022-02-11 21:18 UTC, rorour commented on tests/pkcli/github_test.py
> +    if full_path:
e51ed5ad795072ccb5951e6c909230393ac6dd6c

2022-02-11 21:18 UTC, rorour commented on tests/pkcli/github_test.py
> +
e51ed5ad795072ccb5951e6c909230393ac6dd6c

2022-02-15 20:20 UTC, e-carlin commented
@rorour I made some updates https://github.com/radiasoft/pykern/pull/119/commits/603cb9751d3d13d71b3d9884554a248197798b94 . Let me know if you see any problems. I reworked the regex a bit but my regex skills still need work so maybe I'm missing something yours was covering. Also, I think it simplified the logic to just always use the repo full_name when tagging the issue in the release issue.

2022-02-16 01:08 UTC, robnagler requested changes

2022-02-16 01:08 UTC, robnagler commented on tests/pkcli/github_test.py
> +        f = f'{r.full_name}#{i}'
You want to test both cases, and this only tests, one. We want to see that both issues got added.

This is when I would make it a nested function, something like (see changes below):

```py
def _commit(repo, full_name, issues):
    issues.append(_create_commit(repo, full_name=full_name))
    a = github.issue_update_alpha_pending(github._TEST_REPO)
    pkunit.pkre(issues[-1].title, a)
    pkunit.pkre(issues[-1].link, a)
    
issues = []
_commit(r, False, issues)
_commit(r, True, issues)
```

Then `issues` will be used below.

2022-02-16 01:08 UTC, robnagler commented on tests/pkcli/github_test.py
> +        pkunit.pkre(f, a)
```py
for i in issues:
     # approximate match, but there won't be false positives
     pkunit.pkre(i.link, a)
     pkunit.pkre(i.title, a)
```

2022-02-16 01:08 UTC, robnagler commented on tests/pkcli/github_test.py
> +    return (i.number, t)
```py
return PKDict(link=f'{repo.full_name}#{i}', title=t)
```

2022-02-24 00:43 UTC, robnagler commented
What's the status of this?

2022-02-24 01:08 UTC, e-carlin commented
We worked on it today. I need to review and then I'll loop you in for final review.

2022-02-24 21:46 UTC, e-carlin approved these changes

2022-02-24 21:47 UTC, e-carlin commented
LGTM. @robnagler please give a final review.

2022-02-24 22:53 UTC, robnagler approved these changes

2022-02-24 22:53 UTC, merged