Fix #156: better help message
radiasoft/pykern pull request #160
Opened 2022-04-14 23:01 UTC by gurhar1133

* Now when -h is invoked on a module, the entire docstring is not printed:
```
$ pykern projex -h
usage: pykern projex [-h] {init-rs-tree,init-tree} ...

commands:
  {init-rs-tree,init-tree}
    init-rs-tree        Initialize defaults for RadiaSoft project tree and
                        call `init_tree`
    init-tree           Setup a project tree with: docs, tests, etc., and
                        checkin to git.

optional arguments:
  -h, --help            show this help message and exit
```
* Also when invoked on module, instead of functions listed as ```positional arguments:``` we get ```commands:``` 
* Test updated to reflect this
* Invoking -h on a function within a module remains unchanged eg.:
```
$ pykern projex init_tree -h
usage: pykern projex init-tree [-h]
                               name author author-email description license
                               url

Setup a project tree with: docs, tests, etc., and checkin to git.

    Creates: setup.py, index.rst, project dir, <name>_console.py, etc.
    Overwrites files if they exist without checking.

    Args:
        name (str): short name of the project, e.g. ``pykern``.
        author (str): copyright holder, e.g. ``RadiaSoft LLC``
        author_email (str): how to reach author, e.g. ``pip@pykern.org``
        description (str): one-line summary of project
        license (str): url of license
        url (str): website for project, e.g. http://pykern.org
    

positional arguments:
  name          -
  author        -
  author-email  -
  description   -
  license       -
  url           -

optional arguments:
  -h, --help    show this help message and exit
```

2022-04-15 19:50 UTC, robnagler approved these changes

2022-04-15 19:50 UTC, robnagler commented on pykern/pkcli/__init__.py
> +        formatter = argh.PARSER_FORMATTER(prog=self.prog)
Calling it formatter detracts from readability. `f` is fine.

2022-04-15 19:50 UTC, robnagler commented on pykern/pkcli/__init__.py
> +        self.program = { key: kwargs[key] for key in kwargs }
You should be able to just assign kwargs or PKDict(kwargs). If you are concerned use kwargs.copy() or really concerned: copy.deepcopy(kwargs).

2022-04-15 19:50 UTC, robnagler commented on pykern/pkcli/__init__.py
> +        return r.split('\n')[0]
Temporary not really necessary for such a small function.

2022-04-15 19:50 UTC, robnagler commented on pykern/pkcli/__init__.py
> +    def format_help(self):
Nice

2022-04-15 19:50 UTC, robnagler commented on pykern/pkcli/__init__.py
> +        if not self.description:
Perhaps it would be better to just do this in format_help since you know if there's a description or not.

2022-04-15 19:50 UTC, robnagler commented on pykern/pkcli/__init__.py
> +                            self._mutually_exclusive_groups)
indentation:

f.add_usage(
    self.usage,
    self.actions,
    self._mutually_exclusive_groups,
)

2022-04-15 19:50 UTC, robnagler commented on pykern/pkcli/__init__.py
> +        for action_group in self._action_groups:
action_group to `g` or `a`.

2022-04-15 19:50 UTC, robnagler commented on tests/pkcli_test.py
> +    _dev(rp, ['conf1', '-h'], SystemExit, r'\{cmd1,cmd2\}.*commands', capsys)
add another test case for the problem you are fixing: one line descriptions per subcommand.

2022-04-18 17:07 UTC, gurhar1133 commented
What do you think about the test here? https://github.com/radiasoft/pykern/pull/160/commits/b7c7a5b38ce212c55aed1b2f00ceeaf6f6de3789 @robnagler Maybe something a bit more clever would be better?

2022-04-18 19:08 UTC, robnagler requested changes

2022-04-18 19:08 UTC, robnagler commented on tests/pkcli_test.py
> +    if 'Args' in out:
pkre('Args.*arg1', out, '_______ \n failure to ignore arguments and only print subject. out: {}', out)

2022-04-18 19:08 UTC, robnagler commented on tests/pkcli_data/p1/pkcli/conf1.py
> +    Args: ...
Please fully format the arguments so we can match arg1 in the output.

2022-04-18 20:01 UTC, gurhar1133 commented
Made the changes  
had to invert test ;)

2022-04-18 21:59 UTC, robnagler approved these changes

2022-04-18 21:59 UTC, merged