Fix #268: ignore lines
radiasoft/pykern pull request #271
Opened 2022-08-23 23:45 UTC by gurhar1133

ignore_lines list keyword arg to case_dirs or file_eq will now ignore all lines that match regex in list
test added

2022-08-24 00:45 UTC, robnagler requested changes
There are conflicts you'll need to fix as well.

2022-08-24 00:45 UTC, robnagler commented on pykern/pkunit.py
> +    <https://www.gnu.org/software/findutils/manual/html_node/find_html/posix_002dbasic-regular-expression-syntax.html>_`
Remove this, and specify Args: (below) and say:

ignore_prefix (iterable): `POSIX standard regular expressions <https://www.gnu.org/software/findutils/manual/html_node/find_html/posix_002dbasic-regular-expression-syntax.html>`_ to be passed to ``diff``

The syntax for rST is 

```rst
`phrase <link>`_
```

2022-08-24 15:23 UTC, mkeilman reviewed
Just a few comments, though I could not test because of merge conflicts.

2022-08-24 15:49 UTC, robnagler commented on pykern/pkunit.py
> +                r.append("-I")
I have to say that comprehension always bothered me. Here's a shorter one I just discovered: `filter(None, self._ignore_lines)`. When the filter is `None` returns the truthy values only. `itertools.filterfalse` does the opposite, which is why I tried the first case.

2022-08-24 15:59 UTC, robnagler commented on pykern/pkunit.py
> +                r.append(l)
Again, I was curious. I don't have a lot of experience with itertools:

`list(itertools.chain.from_iterable((itertools.zip_longest((), ('a', 'b', 'c'), fillvalue='-I'))))`

I don't think this is worth it.

2022-08-24 16:02 UTC, robnagler commented on tests/pkunit_test.py
> +        ignore_lines=[r"[0-9]\+xyz"],
Ha ha. I told him to do it the way it is now. I think having the data in files for a "file_eq" test makes more sense.

2022-08-24 17:59 UTC, gurhar1133 commented
@robnagler conflicts resolved

2022-08-24 20:38 UTC, mkeilman approved these changes
lgtm!

2022-08-24 20:46 UTC, robnagler requested changes

2022-08-24 20:46 UTC, robnagler commented on pykern/pkunit.py
> +        for l in (l for l in [l for l in self._ignore_lines if l]):
There are too many `for` loops. This is a better encapsulation, which both shortens the code and separates out a cohesive chunk:

```py
def _cmd():
    if self.is_bytes:
        r = ["cmp"]
    else:
        r = ["diff"]
        for l in self._ignore_lines or ():
            r.extend(("-I", l))
    return r + [str(self._expect_path), str(self._actual_path)]
```

Move `_cmd` inside `_compare`. You don't need to pass self.

`_gen_ignore_lines` is non-descriptive. 

`ignore_lines` could be [], (), None, False, etc. We don't care, it's falsey, and do nothing. 

Use tuples unless you expect the object is going to be modified. 

The elements of ignore_lines must be strings. If someone wants to pass "" as an element, pass that as a value to -I.

2022-08-24 20:46 UTC, robnagler commented on pykern/pkunit.py
> +
no blank line.

2022-08-24 20:46 UTC, robnagler commented on pykern/pkunit.py
> +            c,
`p=subprocess.run(_cmd(), stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True)`

2022-08-24 20:46 UTC, robnagler commented on pykern/pkunit.py
> +{self._comparison_message(p.returncode)}""",
This should be a nested function, too. Describe what it is, and again cohesive modularization. There's an indentation issue in _message (those lines should be left justfied), and combine in a single nested function:

```py
def _failed_msg(process):
        r = "'" + "' '".join(process.args) + f"'\n" + p.stdout + "\n"
        if not (return_code == 1 or self.is_bytes):
            return r + "diff command failed\n"
        if self._expect_is_jinja:
            return r + f"""
Implementation restriction: expect is a jinja template which has been processed to
produce the diff. A simple copy of actual to expect is not possible. You will need to update
the expect jinja template={self._expect_path} manually.
"""
        return r + f"""
to update test data:
    cp '{self._actual_path}' '{self._expect_path}'
"""
```

2022-08-24 22:12 UTC, gurhar1133 commented
@robnagler made changes

2022-08-25 02:25 UTC, robnagler requested changes

2022-08-25 02:25 UTC, robnagler commented on pykern/pkunit.py
> +    def _gen_ignore_lines(self):
not used, delete. same for _message().

2022-08-25 15:29 UTC, gurhar1133 commented on pykern/pkunit.py
> +    def _gen_ignore_lines(self):
oops, sorry i missed those

2022-08-25 15:44 UTC, gurhar1133 commented
@robnagler how bout now?

2022-08-25 15:46 UTC, robnagler approved these changes

2022-08-25 15:47 UTC, merged