Fix #251: pkcli message
radiasoft/pykern pull request #283
Opened 2022-09-30 21:19 UTC by gurhar1133

pkcli.message writes to stderr without raising
includes a test

2022-09-30 22:29 UTC, robnagler requested changes

2022-09-30 22:29 UTC, robnagler commented on pykern/pkcli/__init__.py
> +def message(fmt, *args, **kwargs):
`command_info` is a better name, since it relates to `command_error`.

2022-09-30 22:29 UTC, robnagler commented on tests/pkcli_data/m1.in/x.py
> +pykern.pkcli.message("this is a message")
This is not the intended usage. It should only be called from a pkcli. Better to structure it that way so people don't use it as a example (tests as documentation).

2022-09-30 22:29 UTC, robnagler commented on tests/pkcli_data/m1.in/x.py
> +import pykern.pkcli
Not sure I understand the naming of this. We had p1, p2, and now m1.in. Perhaps just 1.in? The m1 makes me ask "what does m stand for"?

2022-09-30 22:29 UTC, robnagler commented on tests/pkcli_test.py
> +            output="res.txt",
res.txt maybe better x.out?

2022-10-03 16:23 UTC, gurhar1133 commented
made changes @robnagler

2022-10-03 21:15 UTC, robnagler approved these changes

2022-10-03 21:16 UTC, merged