Fix #387 pkdebug fmt spec
radiasoft/pykern pull request #388
Opened 2023-08-14 20:33 UTC by robnagler

2023-08-15 22:39 UTC, e-carlin requested changes

2023-08-15 22:39 UTC, e-carlin commented on pykern/pkdebug.py
> +                    obj, (int, complex, float, decimal.Decimal)
isinstance(obj, numbers.Number) ?

2023-08-15 23:06 UTC, robnagler commented on pykern/pkdebug.py
> +                    obj, (int, complex, float, decimal.Decimal)
bbe5b4b

2023-08-16 00:27 UTC, e-carlin approved these changes

2023-08-16 00:27 UTC, merged