Fix #402: parse for error
radiasoft/pykern pull request #403
Opened 2023-10-05 22:27 UTC by gurhar1133

2023-10-05 22:56 UTC, robnagler requested changes

2023-10-05 22:56 UTC, robnagler commented on tests/pkcli/warning_data/tests/1_test.py
> +from __future__ import absolute_import, division, print_function
`__future__` unnecessary

2023-10-05 22:56 UTC, robnagler commented on tests/pkcli/warning_data/tests/1_test.py
> +:copyright: Copyright (c) 2019 RadiaSoft LLC.  All Rights Reserved.
2023

2023-10-05 22:56 UTC, robnagler commented on tests/pkcli/warning_test.py
> +import pytest
unnecessary import

2023-10-05 22:56 UTC, robnagler commented on tests/pkcli/warning_test.py
> +:copyright: Copyright (c) 2019 RadiaSoft LLC.  All Rights Reserved.
2023

2023-10-05 22:56 UTC, robnagler commented on pykern/pkcli/test.py
> +            if _runtime_warning(output):
This is unnecessary.

2023-10-05 22:56 UTC, robnagler commented on pykern/pkcli/test.py
> +_RUNTIME_WARNING_FAIL = r"RuntimeWarning: coroutine .+ was never awaited"
`r` is unnecessary. The name is `_COROUTINE_NEVER_AWAITED`. It should be a `re.compile`.

2023-10-05 22:56 UTC, robnagler commented on pykern/pkcli/test.py
> +        def _runtime_warning(output):
`_coroutine_never_awaited`

2023-10-05 22:56 UTC, robnagler commented on pykern/pkcli/test.py
> +                    raise AssertionError("coroutine not awaited, warning raised")
I think what should happen is that we should append the FAILURE description to the end of output. We could actually edit the pytest output:

`======================== 3 passed, 2 warnings in 27.88s ========================`

We don't know what failed or passed here, but we can simply replace this line with something like:

```
FAILED: Detected asyncio problem: coroutine was never awaited
```

2023-10-05 22:56 UTC, robnagler commented on tests/pkcli/warning_test.py
> +# -*- coding: utf-8 -*-
This should be in test_data/tests/3_test.py. It should then have a log. It should actually be an asyncio example:

```
def test_coroutine_never_awaited():
    async def _test():
        asyncio.sleep(0)
    asyncio.run(_test)
```

Something like that.

2023-10-05 22:56 UTC, robnagler commented on tests/pkcli/warning_test.py
> +def test_warning(capsys):
This is what pkcli/test_test.py does.

2023-10-13 23:57 UTC, robnagler commented
@gurhar1133 please see my changes an lmk.

2023-10-16 18:19 UTC, gurhar1133 commented
Yes, moving the test to a case dir and using capsys simplifies pkcli/test.py a lot. I removed the unused _sub_output function. lmk if you want me to make more changes

2023-10-16 19:43 UTC, robnagler approved these changes

2023-10-16 19:43 UTC, merged