FIx #400 Stdout feedback if test skipped
radiasoft/pykern pull request #440
Opened 2024-02-02 00:04 UTC by Benbenbenin0

Instead of nothing:
```
 pass
passed=1
```

Now prints for each skipped case:
```
tests/pkcli/sim_test.pytests/pkcli/sim_test.py::test_init_and_run SKIPPED (need to be able ...)
tests/pkcli/sim_test.pytests/pkcli/sim_test.py::test_skip SKIPPED (testing skipped ...)
tests/pkcli/sim_test.pytests/pkcli/sim_test.py::test_skip2 SKIPPED (unconditional skip)
 pass
passed=1
```

Tested with modified `tests/pkcli/sim_test.py`, catches skip() with/without reason and skipif().

@mkeilman wasn't sure between just a warning or actually printing cases, wondering what you think.

2024-02-02 01:47 UTC, robnagler commented
> tests/pkcli/sim_test.pytests/pkcli/sim_test.py::test_init_and_run SKIPPED (need to be able ...)

Maybe construct in a way that looks like other log entryies:

tests/pkcli/sim_test.pytests/pkcli/sim_test.py:555:test_init_and_run

2024-02-02 02:07 UTC, robnagler requested changes
Butting in with some ideas.

2024-02-02 02:07 UTC, robnagler commented on pykern/pkcli/test.py
> +_TEST_SKIPPED = re.compile(".+ SKIPPED \(.+\)")
If you'd like to match more securely, include line start/end, and don't forget `r`:

`re.compile(r"^.+\s+SKIPPED\s+\(.+\)$", flags=re.MULTILINE)`

Also be loose with spaces on parsing. If the output changes to two spaces or tab or something else, `\s` is more robust.

2024-02-02 02:19 UTC, robnagler commented
Also would be good to write a test.

2024-02-06 00:40 UTC, Benbenbenin0 commented
New output:
```
tests/pkcli/sim_test.py pass
tests/pkcli/sim_test.py::test_init_and_run SKIPPED (need to be able ...)
tests/pkcli/sim_test.py::test_skip SKIPPED (unconditional skip)
tests/pkcli/sim_test.py::test_skipif SKIPPED (with reason)
passed=1
```

Thanks @robnagler for the notes, 2 questions:
1) Do you have a suggestion for testing these user messages? Anything inside the skipped test is, well, skipped and I'm not sure about capturing stdout in another test.
2) test1_test.py already has pytest imported, is that the right file for this test?

2024-02-07 15:40 UTC, robnagler commented
> Do you have a suggestion for testing these stdout messages? Anything inside the skipped test is, well, skipped and I'm unsure whether to try capturing output in another test.

Hard to prove a negative, but if you see a specific output from a test that is skipped, then it wasn't skipped. The test could be like:

```py
def test_skip():
    from pykern import pkunit

    pkunit.pkfail("test_skip not skipped")
```

Then you search for "test_skip not skipped" and fail if it is. You shouldn't see a failure either.

> test1_test.py already has pytest imported out of the test_test's, is that the right file for this test?

Create a separate test file (test_data/3_test.py) for this and write a separate case test_skip_output. You probably want a passing test in that file so you see passing and skipped.

2024-02-07 23:11 UTC, Benbenbenin0 commented
@robnagler two more things:
> Then you search for "test_skip not skipped" and fail if it is. You shouldn't see a failure either.
- I assumed this meant search the test_log, am I getting the path correctly in case::test_skip_output()?
- pkfail doesn't seem to print it's msg in the test log until after all test complete, searching for "FAILED" instead.

2024-02-07 23:29 UTC, robnagler commented
You should be able to capsys. See how test_test does that.

2024-02-08 01:07 UTC, Benbenbenin0 commented
@robnagler seems like capsys only captures from the output stream within a test case, meaning I can't see the pkfail output from `test_skip` in a following case.

I'm unsure where you want to do the checking, did you mean:
1) add a file `test_data/tests/3_test.py` containing a skipped case that pkfails with a unique msg
2) add another case to the same file that passes so `3_test.py` has passing and skipped
3) in `test_test.py` or somewhere else add a case `test_skip_output` that fails if capsys output contains the unique msg

2024-02-08 14:43 UTC, robnagler commented
[f29013f](https://github.com/radiasoft/pykern/pull/440/commits/f29013f4c1f65664c38242aac00aea4ad4371f30) fixes the test. Look at the diffs to understand.

Running tests of test infrastructure is very confusing. What I did first was break down test_simple to individual parts to see which part was throwing the exception (incorrectly). The test for exceptions being thrown during conformance clutters things so I like having one pkunit conditional at a time until I understand what's going on.

2024-02-09 00:21 UTC, robnagler commented
@Benbenbenin0 [7f8133a](https://github.com/radiasoft/pykern/pull/440/commits/7f8133a173ae85b0d56712132272f3a3b3c93dda) fixes an interesting problem. Like I said, testing test infrastructure is hard.

2024-02-12 21:05 UTC, Benbenbenin0 commented
@robnagler I reviewed [f29013f](https://github.com/radiasoft/pykern/pull/440/commits/f29013f4c1f65664c38242aac00aea4ad4371f30), makes sense just two questions:
- Why test 1 & 3 then 2 & 3? Is this to test skips within a failing and passing test sequence?
- Why test 1 & 3 individually as well? These are all testing the basic function of pytest, is this to cover individual testing or something more redundant?

I also looked at [7f8133a](https://github.com/radiasoft/pykern/pull/440/commits/7f8133a173ae85b0d56712132272f3a3b3c93dda), makes sense why the CI was failing.

Still need a review from you to merge.

2024-02-12 23:02 UTC, robnagler commented
> Why test 1 & 3 then 2 & 3? Is this to test skips within a failing and passing test sequence?

Yes.

> Why test 1 & 3 individually as well? These are all testing the basic function of pytest, is this to cover individual testing or something more redundant?

We're making sure that calling default_command() with a single test (vs a directory) will produce different results. This definitely testing workflow inside pkcli.test.

2024-02-12 23:03 UTC, robnagler approved these changes

2024-02-12 23:03 UTC, merged